################################################
# base image
################################################
FROM node:12.18.3-alpine3.9

################################################
# workdir
################################################
WORKDIR /usr/src/app

################################################
# copy package.json for dependencies + install + run
################################################
COPY ./nuxt_app/package.json .
COPY ./nuxt_app/package-lock.json .

RUN npm install && npm cache clean --force

COPY ./nuxt_app .

ENV NUXT_HOST: 0.0.0.0
ENV NUXT_PORT: 3000