################################################
# base image
################################################
FROM node:12.18.3-alpine3.9

################################################
# workdir
################################################
WORKDIR /usr/src/app/

################################################
# copy package.json for dependencies + install + run
################################################
COPY ./nuxt_app/package.json .
COPY ./nuxt_app/package-lock.json

RUN npm install

COPY . .

