stages:
    - build-docker
    - test
    - deploy

# ****************************************************************
# build backend django (+ postgis db)
# ****************************************************************
build-backend-django:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - cd backend
        - docker build -f Dockerfile.prod -t $CI_REGISTRY_IMAGE/backend-django:latest .
        - docker tag $CI_REGISTRY_IMAGE/backend-django:latest $CI_REGISTRY_IMAGE/backend-django:$CI_COMMIT_REF_NAME
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/backend-django:$CI_COMMIT_REF_NAME
    when: manual
    only: 
        - tags

# ****************************************************************
# build frontend nuxt
# ****************************************************************
build-frontend-nuxt:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - cd frontend
        - docker build -f Dockerfile.prod -t $CI_REGISTRY_IMAGE/frontend-nuxt:latest .
        - docker tag $CI_REGISTRY_IMAGE/frontend-nuxt:latest $CI_REGISTRY_IMAGE/frontend-nuxt:$CI_COMMIT_REF_NAME
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/frontend-nuxt:$CI_COMMIT_REF_NAME
    when: manual
    only: 
        - tags

# ****************************************************************
# build nginx
# ****************************************************************
build-nginx:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - cd nginx
        - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/nginx:latest .
        - docker tag $CI_REGISTRY_IMAGE/nginx:latest $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME
    when: manual
    only: 
        - tags

# ****************************************************************
# deploy to vps dev
# ****************************************************************
deploy-vps:
    stage: deploy
    tags:
        - vps_dev 
    script:
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE/frontend-nuxt:$CI_COMMIT_REF_NAME
        - docker pull $CI_REGISTRY_IMAGE/backend-django:$CI_COMMIT_REF_NAME
        - docker pull $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME
        - docker-compose -f docker-compose.prod.yml down -v
        - docker-compose -f docker-compose.prod.yml up -d
    when: manual
    only:
        - tags
