stages:
    - build-docker
    - test
    - deploy

build-backend-django:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    variables:
        # Tell docker CLI how to talk to Docker daemon; see
        # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
        DOCKER_HOST: tcp://docker:2375/
        # Use the overlayfs driver for improved performance:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - cd backend
        - docker build -f Dockerfile.prod -t $CI_REGISTRY_IMAGE/backend-django:latest .
        - docker tag $CI_REGISTRY_IMAGE/backend-django:latest $CI_REGISTRY_IMAGE/backend-django:$CI_COMMIT_REF_NAME
        - docker login -u benjamin -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/backend-django:$CI_COMMIT_REF_NAME
    when: manual

build-frontend-nuxt:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - cd frontend
        - docker build -f Dockerfile.prod -t $CI_REGISTRY_IMAGE/frontend-nuxt:latest .
        - docker tag $CI_REGISTRY_IMAGE/frontend-nuxt:latest $CI_REGISTRY_IMAGE/frontend-nuxt:$CI_COMMIT_REF_NAME
        - docker login -u benjamin -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/frontend-nuxt:$CI_COMMIT_REF_NAME
    when: manual

build-nginx:
    tags:
        - build-docker
    stage: build-docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - cd nginx
        - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/nginx:latest .
        - docker tag $CI_REGISTRY_IMAGE/nginx:latest $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME
        - docker login -u benjamin -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_NAME
    when: manual
    only: 
        changes:
            - nginx/*