version: '3.7'

services: 
  django:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes: 
      # for local dev: when changes in polity
      - ./backend/django_app:/usr/src/app/
    ports: 
      - 8000:8000
    env_file: 
      - ./backend/.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - postgis_data:/var/lib/postgis/data/
    environment:
      - POSTGRES_USER=polity
      - POSTGRES_PASSWORD=politydev
      - POSTGRES_DB=polity
  nuxt:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      # for local dev: when changes in polity
      - ./frontend/nuxt_app:/usr/src/app/
    ports:
      - 3000:3000
    env_file: 
      - ./frontend/.env.dev
    command: npm run dev
    depends_on: 
      - django


volumes:
  postgis_data: