version: '3.7'

services: 
  django:
    # which Dockerfile to use, path
    build: 
      context: ./django
      dockerfile: Dockerfile.prod
    ports: 
      - 8000:8000
    env_file: 
      - ./django/.env.prod
    command: gunicorn polity.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    # postgis image for geodjango 
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - postgis_data:/var/lib/postgis/data/
    env_file: 
      - ./postgis/.env.prod
# nginx:
#   build: ./nginx
#   ports:
#     - 1337:80
#   depends_on:
#     - django

volumes:
  postgis_data: