version: '3.7'

services: 

  django:
    # which Dockerfile to use, path
    build: 
      context: ./django
      dockerfile: Dockerfile.prod
    volumes: 
      - django_static_volume:/polity/static
    ports: 
      - 8000:8000
    env_file: 
      - ./django/.env.prod
    command: gunicorn polity.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    # postgis image for geodjango 
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - postgis_data:/var/lib/postgis/data/
    env_file: 
      - ./postgis/.env.prod

  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.prod
    volumes: 
      - nuxt_static_volume:/polity/build/static
    expose: 
      - 3000
    command: serve -s build -l 3000
    depends_on: 
      - django
  
  nginx:
    restart: always
    build: ./nginx
    volumes: 
      - django_static_volume:/polity/django_files/static
      - nuxt_static_volume:/polity/nuxt_files/static
    ports:
      - 80:80
    depends_on:
      - nuxt

volumes:
  postgis_data:
  django_static_volume:
  nuxt_static_volume: