version: '3.7'

services: 

  ###############################
  # BACKEND 
  ###############################
  django:
    container_name: polity_django_prod
    # which Dockerfile to use, path
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    expose: 
      - 8000
    env_file: 
      - ./backend/.env.prod
    command: gunicorn polity.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  ###############################
  # DB: postgis 
  ###############################
  db:
    container_name: polity_db_prod
    # postgis image for geodjango 
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - postgis_data:/var/lib/postgis/data/
    env_file: 
      - ./postgis/.env.prod
  ###############################
  # FRONTEND 
  ###############################
  nuxt:
    container_name: polity_nuxt_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: 
      - nuxt_static_volume:/usr/src/app/static
    expose: 
      - 3000
    command: npm run start
    depends_on: 
      - django
  ###############################
  # NGINX 
  ###############################
  nginx:
    container_name: polity_nginx_prod
    restart: always
    build: ./nginx
    volumes: 
      - django_static_volume:/usr/src/app/django_files/static
      - nuxt_static_volume:/usr/src/app/nuxt_files/static
      - media_volume:/usr/src/app/media_files/uploads
    ports:
      - 80:80
    depends_on:
      - nuxt

volumes:
  postgis_data:
  django_static_volume:
  nuxt_static_volume:
  media_volume: