################################################
# base image
################################################
FROM python:3.8-slim

################################################
# set work directory
################################################
WORKDIR /usr/src/app

################################################
# set environment variables
################################################
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

################################################
# update repository & install dependencies  ####
################################################
RUN apt-get update && \
    # pipenv
    apt-get install -y --no-install-recommends pipenv \
    # uwsgi
    build-essential \
    # dependencies gdal & postgis
    binutils libproj-dev gdal-bin python-gdal python3-gdal \
    # netcat for entrypoint.sh (waiting for db)
    netcat \
    && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

################################################
# copy all to /usr/src/app
################################################
COPY ./django_app . 

################################################
# pipenv
################################################
RUN pipenv install --system --deploy --ignore-pipfile

################################################
# adjust permissions entrypoint + run 
################################################
RUN chmod 777 entrypoint.dev.sh
ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]